### ISSUE TITLE
Rateapp no longer displays saved rankings properly

### ISSUE THREAD

**Issue by jelmerderonde** [SURFpol/pol-harvester#100]
Browser console shows the following error when loading a previously saved ranking:

```
TypeError: "t.getDocumentData(...) is undefined"
    u List.vue:5
    ze VueJS
    u List.vue:4
    VueJS 7
vue.runtime.esm.js:1888
```

**Comment by fako** [comment]
We should write a command that migrates index X to index Y for query rankings

**Comment by fako** [comment]
Command is called: migrate_query_rankings

**Comment by jelmerderonde** [comment]
Had to do with the firewall. And reacreated indices.
