### ISSUE TITLE
Change the Elasticsearch mapping so that more fields also have _keyword field. This will allow us to create charts in Kibana.

### ISSUE THREAD

**Issue by jelmerderonde** [SURFpol/pol-harvester#104]
* Collection
* Mimetype
* Humanized Mimetype

**Comment by fako** [comment]
Hier staat de definitie van de mapping: https://github.com/SURFpol/pol-harvester/blob/master/harvester/search/utils/elastic.py#L36

**Comment by fako** [comment]
Create index met:
* source activate.sh
* cd harvester
* python manage.py create_es_index --recreate --freeze beta

**Comment by fako** [comment]
Misschien iets mis met de .env settings in pol-harvester directory??

**Comment by fako** [comment]
Index configs are stored in the database and need to get deleted if you want an update for an existing index. Existing indices now updated.
