### ISSUE TITLE
Implement OAI-PMH

### ISSUE THREAD

**Issue by jelmerderonde** [SURFpol/pol-harvester#128]
Implement OAI-PMH to harvest EduRep. EduRep has requested us to take make sure that we:

* Do not harvest the same materials unnecessarily multiple times from different environments (dev, test, prod). Instead devise some way to share the materials between environments. Needs discussion?
* Schedule heavy harvests (when we harvest entire sets) to take place during the night.

**Comment by jelmerderonde** [comment]
EduRep has added our test and prod machines to their whitelist

**Comment by fako** [comment]
These things are still open todo's for this ticket. We may want to split these into their own ticket at some point, but wanted to have a listing to begin with
- [ ] Throw errors when an OAI-PMH update fails
