### ISSUE TITLE
Investigate the "multiple technical locations" problem

### ISSUE THREAD

**Issue by fako** [SURFpol/pol-harvester#134]
There are some materials that have multiple locations. We're wondering how often this occurs and if we need to adjust our approach in some way.

**Comment by fako** [comment]
I couldn't really check (yet) if there are differences between the API and OAIPMH, but in the API there are only about 60 materials that have location duplicates and 8 have no location at all. If you read the NL-LOM specification than apparently it's ok to have multiple locations, but the preferred locations should be at the top. So in that case our code is doing fine, because it takes the first location it encounters (within a record). However we can doubt if in our example case (id=oai:surfsharekit.nl:5be6dfeb-b9ad-41a8-b4f5-94b9438e4257) the preferred location is truly the first location, because the source location is actually the bottom location. That would be something to discuss with Sharekit.

**Comment by jelmerderonde** [comment]
Can you get me a list with some examples?

**Comment by fako** [comment]
Sure thing boss ;) 
This is the list of 0 locations:
- surf:oai:surfsharekit.nl:9c6bf810-2dd1-411f-ae0c-b1d65f94e2a7
- surf:oai:surfsharekit.nl:161fcb68-dd16-49f6-b443-6ca6a824ccdb
- surf:oai:surfsharekit.nl:4ddaeb1f-bcb7-49df-82fa-33c3e88a81ee
- surf:oai:surfsharekit.nl:c5f46901-c4bc-4aef-90f3-8863457f868a
- surf:oai:surfsharekit.nl:d3e2d02b-4f67-4a09-97dc-27d951ee79fc
- surf:oai:surfsharekit.nl:82a8f37b-8f15-4117-8dcd-b3317d381230
- surf:oai:surfsharekit.nl:77edac43-0f87-481a-9116-8539442a6fb6
- fontys:oai:surfsharekit.nl:976a12e1-4333-4bfe-a7f6-5b279e63f6d1

**Comment by fako** [comment]
This is a CSV with all multi locations
[multi_locations.csv.zip](https://github.com/SURFpol/pol-harvester/files/4229564/multi_locations.csv.zip)

**Comment by fako** [comment]
I see a pattern! I think you'll spot it pretty quickly too :$
