### ISSUE TITLE
Comparison between Kaldi and commercial speech recognition engines

### ISSUE THREAD

**Issue by fako** [SURFpol/pol-harvester#64]
Quantitative comparison. Use WER's as a measure and the costs, where costs for engineers should be included in the Kaldi costs.

Alternatively to using Google Speech to Text use Youtube API to download subtitles and compare outcomes. Youtube API docs: https://developers.google.com/youtube/v3/docs/captions/download

**Comment by jelmerderonde** [comment]
UvA has already done this and we have the report.
