### ISSUE TITLE
Make comparison with Google possible

### ISSUE THREAD

**Issue by fako** [SURFpol/pol-harvester#69]
Allow Google to index all materials and write some code that calls the Google Search API. These results should then be compared to ranked queries using DCG. We'll compare Google's DCG score to our own.

**Comment by fako** [comment]
Using: https://gist.github.com/bwhite/3726239

**Comment by fako** [comment]
This is an interesting resource that indicates how you can tune a Google Search engine: https://developers.google.com/custom-search/docs/ranking

**Comment by fako** [comment]
This is the output of the analyse_google_search command. Google is not doing too great.

leren leren
***********
[0, 0, 0, 0, 0, 0, 0, 0, 0]
0.0


reflectievaardigheden
*********************
WARNING: no Google search results for 'reflectievaardigheden'
[]
0


feedback geven
**************
[0, 0, 0]
0.0


harmonie
********
[2, 0]
2.0


noteren van muziek
******************
[9]
9.0


depressie
*********
[0, 0]
0.0


didactiek
*********
[0, 7, 0, 0, 7, 0, 7, 0, 7, 0]
14.716440353770007


injecteren
**********
[0]
0.0


learning to learn
*****************
[0, 0, 0, 0, 0, 0, 0]
0.0


reflection skills
*****************
[0]
0.0


giving feedback
***************
[0, 0, 0, 0]
0.0


biology transformation
**********************
WARNING: no Google search results for 'biology transformation'
[]
0


harmony
*******
WARNING: no Google search results for 'harmony'
[]
0


depression
**********
[0]
0.0


musical notes
*************
WARNING: no Google search results for 'musical notes'
[]
0


epidemiology
************
[9, 8, 0, 0]
17.0


gene
****
[0, 0, 0, 0, 0]
0.0

**Comment by fako** [comment]
In the mean time. I've refactored this to use query rankings from the database instead of the old ones from disk

**Comment by jelmerderonde** [comment]
I've added some of the results found by Google to the query rankings in the database.
