### ISSUE TITLE
Given a domain train language model 

### ISSUE THREAD

**Issue by jelmerderonde** [SURFpol/pol-harvester#73]
(for example from wikipedia articles) and merge with Kaldi language model

MIght be useful to start with Verpleegkunde materials (Gezondheid domein)

**Comment by fako** [comment]
We made a language model for Gezondheid and also a basic one for Aardwetenschappen. Very few extra words were recovered (see ticket about building a vocabulary based on a Wikipedia corpus). I didn't put in any effort to create new transcriptions with the new model. I'm not expecting a lot of improvement and it is a huge hassle to manage a different transcription model next to the default at the moment.
