### ISSUE TITLE
Test Machiel's idea for query enrichment: use first x results (tf/idf) as query for a second search

### ISSUE THREAD

**Issue by fako** [SURFpol/pol-harvester#76]
This idea is better known as Pseudo Relevance Feedback (or PRF)

**Comment by fako** [comment]
There is now a analyse_pseudo_relevance_feedback command to see how results improve when applying PRF

**Comment by fako** [comment]
reflectievaardigheden
---------------------
059e20c67dd869997d99272f9fba1f38728d7571
[3]
3.0
---------------------
['lichaamstaal', 'verbatim', 'we']
059e20c67dd869997d99272f9fba1f38728d7571
19acdc8dd88cc7ae22d792af22434fbfbe49fefb
f7cafa54cccf5b11f7fdf48171611fdc88da01d5
b909ab194fdc4acb54518aa4a32321d6b76fbc40
0cdccf026dfafc2a3b57663b47dde90eaa3b7ecb
d3d10dd9323249121f2d271f387b0066ce557f60
9253785147d1a2b2deb46a83def9be9564622864
0e6208171a59b76d9550a41e5b1798027e947f47
eaae719845a1bb582c8cdf7ebcc256b9ffe841b0
47f9b0ac12b3c713de562fb1f1bb8d9341c61cac
[3, 0, 0, 0, 0, 0, 0, 0, 0, 0]
3.0


genetic modification
--------------------
b6f1085673d2b76abdac9a739bfefe5e3513cdad
da612ded156a491f863c7cd454fc1ad4982512f0
fe26e69b018d17c00151d47b3dce611a57e46df5
6292408db05955e0768e9c36a2e701552971247c
6ac0dcdd2518bcb582da9ae2ae8c8b3fb56a8906
b4f16183a50ac6fb755ad9611bd9161446ba3d67
2a1bb33138aa469f0f3f56b4a392d73839423a68
9bac3ecbfb9e516366eaf18a4801e8b74ced15db
416218c8e4ba406507afb591b51df9ebe5a0264b
4d1ab992e0d88abcfed719cd9343a7756e171d05
[5, 5, 5, 4, 5, 0, 0, 0, 5, 3]
19.788445929144842
--------------------
['the', 'of', 'and']
b6f1085673d2b76abdac9a739bfefe5e3513cdad
da612ded156a491f863c7cd454fc1ad4982512f0
fe26e69b018d17c00151d47b3dce611a57e46df5
6292408db05955e0768e9c36a2e701552971247c
9bac3ecbfb9e516366eaf18a4801e8b74ced15db
4d1ab992e0d88abcfed719cd9343a7756e171d05
6ac0dcdd2518bcb582da9ae2ae8c8b3fb56a8906
b4f16183a50ac6fb755ad9611bd9161446ba3d67
970a9833f6cf33ff78609477d8b4a556c23becb3
2a1bb33138aa469f0f3f56b4a392d73839423a68
[5, 5, 5, 4, 0, 3, 5, 0, 0, 0]
18.096243125101022


harmonie
--------
2f4c55ef5047103d2b77e9b01e2a2d49c596ebc0
ffffbbc3943cf9a26b155ad19b6f6aa25c161108
d745a7cb01e50125c22deb3cb5866123e790472f
13d10b06fa031314cdb57362602227dc9f76ab4b
64098edd5e5e907a7e62b0faf7e332518ddbed4e
582f1bab1d9bd46a72f21ae221b54491814705cc
7d3d3ec465321f5853ed2e41e20aa17e2ea99683
c4e80ed9b6910480e7dd8b196a8d9c4adcdc1f2d
1e09534c244d903673af12ed74953cf538fe1726
b54231081cbd0ec97572c0dba91a237a82a2b4d1
[0, 5, 5, 5, 5, 5, 0, 5, 4, 0]
17.670821768206544
--------
['cadensen', 'majeur', 'progressies']
582f1bab1d9bd46a72f21ae221b54491814705cc
64098edd5e5e907a7e62b0faf7e332518ddbed4e
13d10b06fa031314cdb57362602227dc9f76ab4b
ffffbbc3943cf9a26b155ad19b6f6aa25c161108
d745a7cb01e50125c22deb3cb5866123e790472f
c4e80ed9b6910480e7dd8b196a8d9c4adcdc1f2d
e1f0d2e611f0a437eda0c7dfa49858b074dba224
ac1634b2ac1161e95ec2edc95d5eb90ea511836c
08b9ccc11d017a9d104ceff1ddd0f895ec7892d1
a4524bb8ee5366c0c6e66249f628e5c9d8fdf6db
[5, 5, 5, 5, 5, 5, 0, 0, 0, 0]
19.74229559439696


genetische modificatie
----------------------
48e33f976ff57d519aebf9fa5a786499e2659245
400bb3d42624f8470549b8648940b0e8857409ee
6d9b1cf8a959d1a4776e1c51dd27bce33966a6ce
4964700e32bdfb37cc067fc480f11ba83bb58e1a
bcb2f05b84fed58defa65776778e8ada90594da1
ebf9a2f665f1e81ee796a873b4512b32949c218b
86b863784aa653e995681e7c0965cce90d4f308e
4eadd9e0b4676bcd03de65b32e1861d7d52c4197
8677fdf2f2d960a02f4a661a324d8162b09bec0e
af18eddbca3ac51726d2b67675662791a4ff2f0d
[5, 3, 3, 3, 3, 4, 0, 0, 0, 0]
14.232230163872718
----------------------
['landbouw', 'gewassen', 'http']
48e33f976ff57d519aebf9fa5a786499e2659245
400bb3d42624f8470549b8648940b0e8857409ee
6d9b1cf8a959d1a4776e1c51dd27bce33966a6ce
ebf9a2f665f1e81ee796a873b4512b32949c218b
4eadd9e0b4676bcd03de65b32e1861d7d52c4197
4964700e32bdfb37cc067fc480f11ba83bb58e1a
c55f45b0bb1591f02de943bd11ad35efec444618
bcb2f05b84fed58defa65776778e8ada90594da1
87fc5de48c9b042551bb11cbb0ffeb1fd48377b7
ba36d45a78fbbb24f1299d4113ffc70eead212a6
[5, 3, 3, 4, 0, 3, 0, 3, 0, 0]
14.053347682417996


leren leren
-----------
df765ee8947a3bc6ffb2085da246df0c7a3a18af
2b5084f3ec5d80d44d862bde33220448ea1eb995
496a584480154436cf8a60be9fe0a3cc405c5979
1606d3c04480bc5f4d3d5c481f3c2d2de482675b
0ca96f07a271bd53a60a55b0260792b23be524f0
c85ead91c2abf330a21d8029108554a5d2deb829
544bcff861ed4859e699ed8218b9e6eba9d29546
aa2a14243ef2fe5e753237d7a8b61d7ece3346d1
2e861fd1c6ea092bb50ba5978889aa3523bf021d
095d0d1523193c0e043d3e9342c0b0a23594fbee
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
0.0
-----------
['ontdekkend', 'icto', 'dat']
496a584480154436cf8a60be9fe0a3cc405c5979
5d7f20bc33675e7b4cf5072e856e817bf791c409
8b0b26574e0165f02a732696aeef3024e99a83a5
8a1d475fd347196612a1db53f4569103380c2cee
1606d3c04480bc5f4d3d5c481f3c2d2de482675b
0ca96f07a271bd53a60a55b0260792b23be524f0
c85ead91c2abf330a21d8029108554a5d2deb829
544bcff861ed4859e699ed8218b9e6eba9d29546
aa2a14243ef2fe5e753237d7a8b61d7ece3346d1
2e861fd1c6ea092bb50ba5978889aa3523bf021d
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
0.0


muzieknotatie
-------------
a3548a796e285d7795164072fe584357475110b4
e30cde4b9ddd32f6ec14d31d9df44f6c0bd139f5
da6c592a677680c641d83bfd2b1dc8f2c1f95211
fe269893b6937ffb5895e2216537170238cf7bb3
4ef3f387520f4db435795748d77e81e3ef992beb
30fbc180ee0be330716940828efee0e9da077080
f9a9d6b26f3962fd51c792213822dbdf16b3a97b
f5e1d449a4464ba7141c5679bdc66b59df4c88b0
f1e6260cf3e8a3fa8ecbb9dd383fb6e38cb359d2
b63da68aeb30b84491cbfc7d91832c62f4fea613
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
0.0
-------------
['enrolment', 'audiobewerking', 'access']
a3548a796e285d7795164072fe584357475110b4
e30cde4b9ddd32f6ec14d31d9df44f6c0bd139f5
da6c592a677680c641d83bfd2b1dc8f2c1f95211
fe269893b6937ffb5895e2216537170238cf7bb3
4ef3f387520f4db435795748d77e81e3ef992beb
30fbc180ee0be330716940828efee0e9da077080
f5e1d449a4464ba7141c5679bdc66b59df4c88b0
d58ebdb631c6ce888be44277df2125417bb25afd
f9a9d6b26f3962fd51c792213822dbdf16b3a97b
f1e6260cf3e8a3fa8ecbb9dd383fb6e38cb359d2
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
0.0


harmony
-------
2f4c55ef5047103d2b77e9b01e2a2d49c596ebc0
7d3d3ec465321f5853ed2e41e20aa17e2ea99683
4a1dd26b16eeae40e8bb5e7aa9be379a0650b2c9
1d091d56e951e14b18f4b8a06b5b6aa8a5045ddd
e24c8df28483889dcf80102d13b82fbc073ce8ba
d52f98f1f598509f6e18a8a788963708a24634ac
388e5be19fd6cb24126ded21a66d690533dec6df
aa2a61264994e15ef3efc8a2040cd08e33911cbc
f3da2e7b135bbfd7d59c8136d890d3729e1fbdae
be02d85cda842cb255ec682cdb31a19a5891eba6
[5, 5, 5, 4, 5, 4, 4, 4, 4, 4]
24.07958435872668
-------
['the', 'of', 'thirds']
1d091d56e951e14b18f4b8a06b5b6aa8a5045ddd
2f4c55ef5047103d2b77e9b01e2a2d49c596ebc0
7d3d3ec465321f5853ed2e41e20aa17e2ea99683
633ca8026256dae257b5660c923fc5b544c14e8e
44ce63146183e10b9f566d9e8058bc97cf2d009f
593112d2cf64471fe0f957f2636f9a8030d975a4
e79a66d5df79e93ddcf96fd68f9c0a4c7087ee52
6586fe5d1c92026afd01c8757827aedb15364781
d89391ea22ec6e1c6c7d9d7d65a861d2f69e2574
3365677273aa68abad78c0f925bafee70c375fea
[4, 5, 5, 4, 4, 0, 0, 0, 0, 0]
15.87735500015086


feedback geven
--------------
93ac84d1e24d0a3d5d5a9c7b23dd79dbb8201e80
cb032604d3e78155fea2d69816bb2ab7d3d3a2b2
0d7399ece1cbbb44d3565b664c7c155d94665c33
ba4a7de347a02699096257a15d06fc13aaa2033f
c09d3a9cfcf6e6fddf8be80ad17841dca3f8bef9
9aea9ca860a8b7155aa8d946d4f308e91c4b0763
57f87a85f4424ea61939d4d13fa6d0e554cadaab
c554b0b111cdcb6e5f418189dc0fc4d4cb52c486
824868d89109da15a2d21cd14e133d8d4da7196b
f7cafa54cccf5b11f7fdf48171611fdc88da01d5
[5, 5, 5, 4, 0, 0, 0, 0, 0, 0]
15.154648767857287
--------------
['ik', 'je', 'dat']
93ac84d1e24d0a3d5d5a9c7b23dd79dbb8201e80
cb032604d3e78155fea2d69816bb2ab7d3d3a2b2
8a1d475fd347196612a1db53f4569103380c2cee
ba4a7de347a02699096257a15d06fc13aaa2033f
c09d3a9cfcf6e6fddf8be80ad17841dca3f8bef9
243fb28aa2e59f591dc6e54707066303f4ade009
0d7399ece1cbbb44d3565b664c7c155d94665c33
ac99fb49d11e751a2f8f4c4a4495ba73fccb31f8
41e6906f81c934c40083ea947f5e029007ab5600
cea41c564948e2187d49b7e3c81e4c49a4ea1636
[5, 5, 3, 4, 0, 5, 5, 5, 3, 4]
21.42527051210697


noteren van muziek
------------------
5388e21b2dfbab60738ef0f309f4adb3c8225000
0b07e272b310cc5c81491b30fb01430550fdaa1d
eebd120aab7da93a1ef109ecff3ee574b71b61e1
035f930e8527677d17385e5ccc1cf897900eefeb
81f72e6d7d324c4bb4ec112b1a33ada08a7894d8
746e71bea29e02941d2a9c2f7c896015c3deb808
b63da68aeb30b84491cbfc7d91832c62f4fea613
fe269893b6937ffb5895e2216537170238cf7bb3
30fbc180ee0be330716940828efee0e9da077080
a3548a796e285d7795164072fe584357475110b4
[0, 0, 0, 0, 0, 0, 5, 5, 5, 5]
6.530176964455327
------------------
['je', 'dat', 'kinderen']
8a1d475fd347196612a1db53f4569103380c2cee
52fab9a080c0eaed443011aaac4480b2bb230c95
eebd120aab7da93a1ef109ecff3ee574b71b61e1
035f930e8527677d17385e5ccc1cf897900eefeb
746e71bea29e02941d2a9c2f7c896015c3deb808
81f72e6d7d324c4bb4ec112b1a33ada08a7894d8
2fadfded37e84370f023015acedbbdf7b8afc4e0
5388e21b2dfbab60738ef0f309f4adb3c8225000
0b07e272b310cc5c81491b30fb01430550fdaa1d
9562d7c258613a8dda1a74bb46a88c81d23cc1b9
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
0.0

**Comment by fako** [comment]
To improve on the enrichments it might be a good idea to create one big stopwords list and filter them out. However selecting a good stop words list turns out to be an art in itself: https://aclweb.org/anthology/W18-2502

**Comment by jelmerderonde** [comment]
I've added some of the results to the query rankings in the database.
