### ISSUE TITLE
Use ConceptNet or similar tool by dbpedia to enrich query

### ISSUE THREAD

**Issue by fako** [SURFpol/pol-harvester#78]
As a first test case we'll be adding the synonyms to queries

**Comment by fako** [comment]
reflectievaardigheden
---------------------
Result ids:
-  059e20c67dd869997d99272f9fba1f38728d7571

Ratings of results: [3]
DCG: 3.0
*********************
Applied enrichments: []
Result ids:
-  059e20c67dd869997d99272f9fba1f38728d7571

Ratings of results: [3]
DCG: 3.0


genetic modification
--------------------
Result ids:
-  b6f1085673d2b76abdac9a739bfefe5e3513cdad
-  da612ded156a491f863c7cd454fc1ad4982512f0
-  fe26e69b018d17c00151d47b3dce611a57e46df5
-  6292408db05955e0768e9c36a2e701552971247c
-  6ac0dcdd2518bcb582da9ae2ae8c8b3fb56a8906
-  b4f16183a50ac6fb755ad9611bd9161446ba3d67
-  2a1bb33138aa469f0f3f56b4a392d73839423a68
-  9bac3ecbfb9e516366eaf18a4801e8b74ced15db
-  416218c8e4ba406507afb591b51df9ebe5a0264b
-  4d1ab992e0d88abcfed719cd9343a7756e171d05

Ratings of results: [5, 5, 5, 4, 5, 0, 0, 0, 5, 3]
DCG: 19.788445929144842
********************
Applied enrichments: ['transmitted', 'genic', 'genetical', 'genealogical', 'genic', 'hereditary', 'adjustment', 'qualifying', 'limiting', 'alteration', 'change', 'accident']
Result ids:
-  b6f1085673d2b76abdac9a739bfefe5e3513cdad
-  4d1ab992e0d88abcfed719cd9343a7756e171d05
-  a329d8328109c884b83a372e3c7ef6889d8c7a5c
-  fe26e69b018d17c00151d47b3dce611a57e46df5
-  b56c6b39025f99ab094ea5e57e3611ffe3f1dc6b
-  416218c8e4ba406507afb591b51df9ebe5a0264b
-  4dc7c22ffd942a6e4615ec3fb297f57d87c8320c
-  da612ded156a491f863c7cd454fc1ad4982512f0
-  6292408db05955e0768e9c36a2e701552971247c
-  240964a55b5b0a64f08eebe8eeac622407f24d94

Ratings of results: [5, 3, 3, 5, 0, 5, 3, 5, 4, 0]
DCG: 18.324201032020728


harmonie
--------
Result ids:
-  2f4c55ef5047103d2b77e9b01e2a2d49c596ebc0
-  ffffbbc3943cf9a26b155ad19b6f6aa25c161108
-  d745a7cb01e50125c22deb3cb5866123e790472f
-  13d10b06fa031314cdb57362602227dc9f76ab4b
-  64098edd5e5e907a7e62b0faf7e332518ddbed4e
-  582f1bab1d9bd46a72f21ae221b54491814705cc
-  7d3d3ec465321f5853ed2e41e20aa17e2ea99683
-  c4e80ed9b6910480e7dd8b196a8d9c4adcdc1f2d
-  1e09534c244d903673af12ed74953cf538fe1726
-  b54231081cbd0ec97572c0dba91a237a82a2b4d1

Ratings of results: [0, 5, 5, 5, 5, 5, 0, 5, 4, 0]
DCG: 17.670821768206544
********
Applied enrichments: ['muziekkorps']
Result ids:
-  ffffbbc3943cf9a26b155ad19b6f6aa25c161108
-  d745a7cb01e50125c22deb3cb5866123e790472f
-  13d10b06fa031314cdb57362602227dc9f76ab4b
-  64098edd5e5e907a7e62b0faf7e332518ddbed4e
-  582f1bab1d9bd46a72f21ae221b54491814705cc
-  2f4c55ef5047103d2b77e9b01e2a2d49c596ebc0
-  7d3d3ec465321f5853ed2e41e20aa17e2ea99683
-  c4e80ed9b6910480e7dd8b196a8d9c4adcdc1f2d
-  1e09534c244d903673af12ed74953cf538fe1726
-  b54231081cbd0ec97572c0dba91a237a82a2b4d1

Ratings of results: [5, 5, 5, 5, 5, 0, 0, 5, 4, 0]
DCG: 20.736557732033834


genetische modificatie
----------------------
Result ids:
-  48e33f976ff57d519aebf9fa5a786499e2659245
-  400bb3d42624f8470549b8648940b0e8857409ee
-  6d9b1cf8a959d1a4776e1c51dd27bce33966a6ce
-  4964700e32bdfb37cc067fc480f11ba83bb58e1a
-  bcb2f05b84fed58defa65776778e8ada90594da1
-  ebf9a2f665f1e81ee796a873b4512b32949c218b
-  86b863784aa653e995681e7c0965cce90d4f308e
-  4eadd9e0b4676bcd03de65b32e1861d7d52c4197
-  8677fdf2f2d960a02f4a661a324d8162b09bec0e
-  af18eddbca3ac51726d2b67675662791a4ff2f0d

Ratings of results: [5, 3, 3, 3, 3, 4, 0, 0, 0, 0]
DCG: 14.232230163872718
**********************
Applied enrichments: ['adaptatie', 'wijziging', 'adaptatie', 'aanpassing', 'bewerking']
Result ids:
-  48e33f976ff57d519aebf9fa5a786499e2659245
-  400bb3d42624f8470549b8648940b0e8857409ee
-  b3ad7d52cb20a6f7a2616c885738a35afc6477d1
-  4ff0c6c819df562820256c4ced501bfe949867e8
-  395eafeaca308c99c61465e019a354c2966e6c38
-  6d9b1cf8a959d1a4776e1c51dd27bce33966a6ce
-  4eadd9e0b4676bcd03de65b32e1861d7d52c4197
-  4964700e32bdfb37cc067fc480f11ba83bb58e1a
-  159dfb0ad2ca54bbfcd26b02225c6ab386bbc52a
-  bcb2f05b84fed58defa65776778e8ada90594da1

Ratings of results: [5, 3, 0, 0, 0, 3, 0, 3, 0, 3]
DCG: 11.063648408695569


leren leren
-----------
Result ids:
-  df765ee8947a3bc6ffb2085da246df0c7a3a18af
-  2b5084f3ec5d80d44d862bde33220448ea1eb995
-  496a584480154436cf8a60be9fe0a3cc405c5979
-  1606d3c04480bc5f4d3d5c481f3c2d2de482675b
-  0ca96f07a271bd53a60a55b0260792b23be524f0
-  c85ead91c2abf330a21d8029108554a5d2deb829
-  544bcff861ed4859e699ed8218b9e6eba9d29546
-  aa2a14243ef2fe5e753237d7a8b61d7ece3346d1
-  2e861fd1c6ea092bb50ba5978889aa3523bf021d
-  095d0d1523193c0e043d3e9342c0b0a23594fbee

Ratings of results: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DCG: 0.0
***********
Applied enrichments: ['bijbrengen', 'aanleren', 'horen', 'studeren', 'doceren', 'studeren', 'onderwijzen', 'scholen', 'bijbrengen', 'taai', 'onderwijzen', 'aanleren', 'bijbrengen', 'aanleren', 'horen', 'studeren', 'doceren', 'studeren', 'onderwijzen', 'scholen', 'bijbrengen', 'taai', 'onderwijzen', 'aanleren']
Result ids:
-  3472ee6d43699ff0d7136925c18a43d69f2ce967
-  d70d84500cce4d5c27067942645b43f4214c658e
-  5dca6b4ca737296eb33bfde043ef06ef6f991325
-  8ab38fd70878ca8bf93593dee654d379a670ddc4
-  3992cf6665f5203477f69eef4ea43fbbf4921757
-  417d97254392022e6626734ed30da0be0526242c
-  e67342ecc3030b58434333790494992814c2ee53
-  476cb4a76edf0c226c50763bf1a7655b6e1c8220
-  2b5084f3ec5d80d44d862bde33220448ea1eb995
-  cff6f955d8292ab49778b0c3d01eedf7fbcf263e

Ratings of results: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DCG: 0.0


muzieknotatie
-------------
Result ids:
-  a3548a796e285d7795164072fe584357475110b4
-  e30cde4b9ddd32f6ec14d31d9df44f6c0bd139f5
-  da6c592a677680c641d83bfd2b1dc8f2c1f95211
-  fe269893b6937ffb5895e2216537170238cf7bb3
-  4ef3f387520f4db435795748d77e81e3ef992beb
-  30fbc180ee0be330716940828efee0e9da077080
-  f9a9d6b26f3962fd51c792213822dbdf16b3a97b
-  f5e1d449a4464ba7141c5679bdc66b59df4c88b0
-  f1e6260cf3e8a3fa8ecbb9dd383fb6e38cb359d2
-  b63da68aeb30b84491cbfc7d91832c62f4fea613

Ratings of results: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DCG: 0.0
*************
Applied enrichments: []
Result ids:
-  a3548a796e285d7795164072fe584357475110b4
-  e30cde4b9ddd32f6ec14d31d9df44f6c0bd139f5
-  da6c592a677680c641d83bfd2b1dc8f2c1f95211
-  fe269893b6937ffb5895e2216537170238cf7bb3
-  4ef3f387520f4db435795748d77e81e3ef992beb
-  30fbc180ee0be330716940828efee0e9da077080
-  f9a9d6b26f3962fd51c792213822dbdf16b3a97b
-  f5e1d449a4464ba7141c5679bdc66b59df4c88b0
-  f1e6260cf3e8a3fa8ecbb9dd383fb6e38cb359d2
-  b63da68aeb30b84491cbfc7d91832c62f4fea613

Ratings of results: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DCG: 0.0


harmony
-------
Result ids:
-  2f4c55ef5047103d2b77e9b01e2a2d49c596ebc0
-  7d3d3ec465321f5853ed2e41e20aa17e2ea99683
-  4a1dd26b16eeae40e8bb5e7aa9be379a0650b2c9
-  1d091d56e951e14b18f4b8a06b5b6aa8a5045ddd
-  e24c8df28483889dcf80102d13b82fbc073ce8ba
-  d52f98f1f598509f6e18a8a788963708a24634ac
-  388e5be19fd6cb24126ded21a66d690533dec6df
-  aa2a61264994e15ef3efc8a2040cd08e33911cbc
-  f3da2e7b135bbfd7d59c8136d890d3729e1fbdae
-  be02d85cda842cb255ec682cdb31a19a5891eba6

Ratings of results: [5, 5, 5, 4, 5, 4, 4, 4, 4, 4]
DCG: 24.07958435872668
*******
Applied enrichments: ['concord', 'musical harmony', 'harmoniousness', 'concordance', 'concord', 'concordance', 'h hr', 'serenity', 'cacophony', 'h hr', 'accordance', 'harmony']
Result ids:
-  2f4c55ef5047103d2b77e9b01e2a2d49c596ebc0
-  7d3d3ec465321f5853ed2e41e20aa17e2ea99683
-  4a1dd26b16eeae40e8bb5e7aa9be379a0650b2c9
-  240964a55b5b0a64f08eebe8eeac622407f24d94
-  e24c8df28483889dcf80102d13b82fbc073ce8ba
-  f9c1c6f27e79fcca3a20ff72a4620412afc53bf8
-  388e5be19fd6cb24126ded21a66d690533dec6df
-  f3da2e7b135bbfd7d59c8136d890d3729e1fbdae
-  aa2a61264994e15ef3efc8a2040cd08e33911cbc
-  a3ac92b9b5cf7f7e325eb531dee8489d347d705d

Ratings of results: [5, 5, 5, 0, 5, 0, 4, 4, 4, 0]
DCG: 19.32805314713259


feedback geven
--------------
Result ids:
-  93ac84d1e24d0a3d5d5a9c7b23dd79dbb8201e80
-  cb032604d3e78155fea2d69816bb2ab7d3d3a2b2
-  0d7399ece1cbbb44d3565b664c7c155d94665c33
-  ba4a7de347a02699096257a15d06fc13aaa2033f
-  c09d3a9cfcf6e6fddf8be80ad17841dca3f8bef9
-  9aea9ca860a8b7155aa8d946d4f308e91c4b0763
-  57f87a85f4424ea61939d4d13fa6d0e554cadaab
-  c554b0b111cdcb6e5f418189dc0fc4d4cb52c486
-  824868d89109da15a2d21cd14e133d8d4da7196b
-  f7cafa54cccf5b11f7fdf48171611fdc88da01d5

Ratings of results: [5, 5, 5, 4, 0, 0, 0, 0, 0, 0]
DCG: 15.154648767857287
**************
Applied enrichments: ['verlenen', 'beschenken', 'begiftigen', 'opleveren', 'schenken', 'gunnen', 'doneren', 'verschaffen', 'toebrengen']
Result ids:
-  93ac84d1e24d0a3d5d5a9c7b23dd79dbb8201e80
-  cb032604d3e78155fea2d69816bb2ab7d3d3a2b2
-  243fb28aa2e59f591dc6e54707066303f4ade009
-  8a1d475fd347196612a1db53f4569103380c2cee
-  0d7399ece1cbbb44d3565b664c7c155d94665c33
-  ac99fb49d11e751a2f8f4c4a4495ba73fccb31f8
-  84150be00727da69a58f6606397c8e8e2d6653cd
-  41e6906f81c934c40083ea947f5e029007ab5600
-  cea41c564948e2187d49b7e3c81e4c49a4ea1636
-  ba4a7de347a02699096257a15d06fc13aaa2033f

Ratings of results: [5, 5, 5, 3, 5, 5, 0, 3, 4, 4]
DCG: 22.2082750841958


noteren van muziek
------------------
Result ids:
-  5388e21b2dfbab60738ef0f309f4adb3c8225000
-  0b07e272b310cc5c81491b30fb01430550fdaa1d
-  eebd120aab7da93a1ef109ecff3ee574b71b61e1
-  035f930e8527677d17385e5ccc1cf897900eefeb
-  81f72e6d7d324c4bb4ec112b1a33ada08a7894d8
-  746e71bea29e02941d2a9c2f7c896015c3deb808
-  b63da68aeb30b84491cbfc7d91832c62f4fea613
-  fe269893b6937ffb5895e2216537170238cf7bb3
-  30fbc180ee0be330716940828efee0e9da077080
-  a3548a796e285d7795164072fe584357475110b4

Ratings of results: [0, 0, 0, 0, 0, 0, 5, 5, 5, 5]
DCG: 6.530176964455327
******************
Applied enrichments: ['opschrijven', 'aantekenen', 'teboekstellen', 'aantekenen', 'toonkunst']
Result ids:
-  746e71bea29e02941d2a9c2f7c896015c3deb808
-  5388e21b2dfbab60738ef0f309f4adb3c8225000
-  0b07e272b310cc5c81491b30fb01430550fdaa1d
-  eebd120aab7da93a1ef109ecff3ee574b71b61e1
-  035f930e8527677d17385e5ccc1cf897900eefeb
-  81f72e6d7d324c4bb4ec112b1a33ada08a7894d8
-  b63da68aeb30b84491cbfc7d91832c62f4fea613
-  fe269893b6937ffb5895e2216537170238cf7bb3
-  30fbc180ee0be330716940828efee0e9da077080
-  a3548a796e285d7795164072fe584357475110b4

Ratings of results: [0, 0, 0, 0, 0, 0, 5, 5, 5, 5]
DCG: 6.530176964455327

**Comment by jelmerderonde** [comment]
I've added some results to the ranked queries in the database.

Especially the query "leren leren" had a lot of extra results than were not already in the rankings.
