### ISSUE TITLE
Look at which fields are most relevant for Elastic Search

### ISSUE THREAD

**Issue by fako** [SURFpol/pol-harvester#84]
Ik heb het command gerunt en de output staat klaar (zie Slack)

**Comment by jelmerderonde** [comment]
I've made the graphs using the code in: https://github.com/SURFpol/pol-harvester/tree/master/research/rankings.  Results are in the README of that directory. So far it seems that the most important fields are title_plain, title and text. We should rerun this experiment when we have more rankings.
