### ISSUE TITLE
Handle file types in a way that Edurep/zoekportal does. Add a filtype field, which we try to fill using mapping from either mimetype or extension. Mimetype can sometimes be not available.

### ISSUE THREAD

**Issue by jelmerderonde** [SURFpol/pol-harvester#94]
Files that are part of IMSCC (or IMSCP) no longer go through Tika separately. This is why we can't be certain of their mime_type (anymore)

Mime type is rather ambiguous with video's. Youtube offers 10 different formats, so what is the mime_type in that case?

**Comment by fako** [comment]
We assumed that Edurep has some sort of way to bring a mime_type back to a file_type, but in fact this happens inside of Zoekportaal. So we should sync the definition over there with our own. I did implement the "read from extension if mime_type is missing" part of this story

**Comment by jelmerderonde** [comment]
Did we sync over the definitions?
